### ISSUE TITLE
Database generation from YAML schema : handle edge case notation for arrays

### ISSUE THREAD

**Issue by lperamo** [lperamo/otra#18]
**Is your feature request related to a problem? Please describe.**
When we write a `schema.yml` to generate a database for OTRA, if we use the `index` key like this : 
```yaml
indexes:
  user_mail_idx:
    columns: mail
```
It does not work as OTRA is waiting for arrays.
This, for example, currently works : 
```yaml
indexes:
  user_mail_idx:
    columns:
      - mail
```

**Solution**
We should either force the string to be an array in OTRA (probably the best solution)
OR put a message to give the right syntax
OR/AND document it if it is a blocking issue.
